# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jadwal_donor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        # ===================== STYLE =======================
        MainWindow.setStyleSheet("""
        QMainWindow {
            background-color: #f1f1f1;
            font-family: "Segoe UI";
        }

        QWidget#panel {
            background-color: white;
            border-radius: 15px;
            border: 1px solid #d0d0d0;
        }

        QLabel {
            font-weight: 600;
        }

        QPushButton {
            background-color: #c00000;
            color: white;
            border-radius: 10px;
            font-weight: 600;
            height: 32px;
        }
        QPushButton:hover {
            background-color: #a00000;
        }

        QListWidget {
            border: 1px solid #c0c0c0;
            border-radius: 6px;
            padding: 4px;
            font-size: 10pt;
        }
        """)

        # ==================== WIDGET ========================
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Panel Putih
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 80, 258, 348))
        self.widget.setObjectName("panel")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(15, 10, 15, 10)
        self.verticalLayout.setSpacing(12)

        # ==================== LABEL TITLE ====================
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size: 13pt; color: #c00000; font-weight: 700;")
        self.verticalLayout.addWidget(self.label)

        # ==================== LABEL SUB ====================
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setStyleSheet("font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_2)

        # ==================== LIST WIDGET ====================
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.verticalLayout.addWidget(self.listWidget)

        # ==================== BUTTON ========================
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.verticalLayout.addWidget(self.pushButton)

        MainWindow.setCentralWidget(self.centralwidget)

        # ================= MENUBAR & STATUS =================
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # ====================== TEXT ============================
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jadwal Donor Darah"))
        self.label.setText(_translate("MainWindow", "LIHAT JADWAL PENDONOR"))
        self.label_2.setText(_translate("MainWindow", "Jadwal Donor"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
