# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pendonor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #F2F2F2;")  # Background abu muda

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # ---------- CARD / WIDGET UTAMA -----------
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 140, 260, 240))
        self.widget.setStyleSheet("""
            QWidget{
                background-color: white;
                border-radius: 15px;
            }
        """)
        self.widget.setObjectName("widget")

        # Layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(18)

        # Judul
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("""
            QLabel {
                color: #8A0000;
                font-size: 16pt;
                font-weight: bold;
            }
        """)
        self.verticalLayout.addWidget(self.label)

        # Sub Judul 1
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setStyleSheet("""
            QLabel {
                color: #333;
                font-size: 10pt;
                font-weight: 600;
            }
        """)
        self.verticalLayout.addWidget(self.label_3)

        # Button 1
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.pushButton.setStyleSheet("""
            QPushButton{
                background-color: #B30000;
                color: white;
                border-radius: 10px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #8A0000;
            }
        """)
        self.verticalLayout.addWidget(self.pushButton)

        # Sub Judul 2
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setStyleSheet("""
            QLabel {
                color: #333;
                font-size: 10pt;
                font-weight: 600;
            }
        """)
        self.verticalLayout.addWidget(self.label_2)

        # Button 2
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(125, 30))
        self.pushButton_2.setStyleSheet("""
            QPushButton{
                background-color: #B30000;
                color: white;
                border-radius: 10px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #8A0000;
            }
        """)
        self.verticalLayout.addWidget(self.pushButton_2)

        # Menu Bar & Status Bar (Default)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # ---------- Text / Tulisan Label ----------
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PENDONOR"))
        self.label_3.setText(_translate("MainWindow", "Pendaftaran Jadwal Donor"))
        self.pushButton.setText(_translate("MainWindow", "Pilih"))
        self.label_2.setText(_translate("MainWindow", "Lihat Jadwal Donor"))
        self.pushButton_2.setText(_translate("MainWindow", "Pilih"))

# ---------- Run App ----------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
