# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendaftaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        # ===== GLOBAL STYLE =====
        MainWindow.setStyleSheet("""
        QMainWindow {
            background-color: #f1f1f1;
            font-family: "Segoe UI";
        }
        QWidget#formPanel {
            background-color: white;
            border-radius: 15px;
            border: 1px solid #d0d0d0;
        }
        QLineEdit, QComboBox {
            border: 1px solid #c0c0c0;
            border-radius: 6px;
            padding-left: 6px;
            font-size: 10pt;
            height: 24px;
        }
        QPushButton {
            background-color: #c00000;
            color: white;
            border-radius: 10px;
            font-weight: 600;
            height: 32px;
        }
        QPushButton:hover {
            background-color: #a00000;
        }
        """)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # PANEL FORM
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 100, 220, 350))
        self.widget.setObjectName("formPanel")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(20, 15, 20, 15)
        self.verticalLayout.setSpacing(15)

        # ============ TITLE ============
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        # ============ NAME ============
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.verticalLayout.addWidget(self.label_2)

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 20))
        self.verticalLayout.addWidget(self.lineEdit)

        # ============ BLOOD ============
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.verticalLayout.addWidget(self.label_3)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(180, 20))
        self.verticalLayout.addWidget(self.lineEdit_2)

        # ============ BIRTH DATE ============
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.verticalLayout.addWidget(self.label_4)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(180, 20))
        self.verticalLayout.addWidget(self.lineEdit_3)

        # ============ SCHEDULE ============
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.verticalLayout.addWidget(self.label_5)

        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(125, 25))
        self.verticalLayout.addWidget(self.comboBox)

        # ============ BUTTON ============
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.verticalLayout.addWidget(self.pushButton)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pendaftaran Donor Darah"))
        self.label.setText(_translate("MainWindow", "<p align='center'><span style='font-size:13pt; font-weight:700; color:#c00000;'>PENDAFTARAN</span></p>"))
        self.label_2.setText(_translate("MainWindow", "<p align='center'><span style='font-size:9pt; font-weight:600;'>Nama Pendonor</span></p>"))
        self.label_3.setText(_translate("MainWindow", "<p align='center'><span style='font-size:9pt; font-weight:600;'>Golongan Darah</span></p>"))
        self.label_4.setText(_translate("MainWindow", "<p align='center'><span style='font-size:9pt; font-weight:600;'>Tanggal Lahir</span></p>"))
        self.label_5.setText(_translate("MainWindow", "<p align='center'><span style='font-size:9pt; font-weight:600;'>Jadwal Donor</span></p>"))
        self.pushButton.setText(_translate("MainWindow", "Daftar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

