# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_petugas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        # STYLE ---------------------------------------
        MainWindow.setStyleSheet("""
        QMainWindow {
            background-color: #f1f1f1;
            font-family: "Segoe UI";
        }

        QWidget#panel {
            background-color: white;
            border-radius: 15px;
            border: 1px solid #d0d0d0;
        }

        QLabel {
            font-weight: 600;
        }

        QPushButton {
            background-color: #c00000;
            color: white;
            border-radius: 10px;
            font-weight: 600;
            height: 32px;
        }
        QPushButton:hover {
            background-color: #a00000;
        }
        """)

        # WIDGET ---------------------------------------
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 130, 210, 255))
        self.widget.setObjectName("panel")  # <--- panel putih

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(20)

        # TITLE ---------------------------------------
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size: 14pt; color: #c00000; font-weight: 700;")
        self.verticalLayout.addWidget(self.label)

        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setStyleSheet("font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_4)

        # MENU 1 ---------------------------------------
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_2)

        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 30))
        self.verticalLayout.addWidget(self.pushButton)

        # MENU 2 ---------------------------------------
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_3)

        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(180, 30))
        self.verticalLayout.addWidget(self.pushButton_2)

        MainWindow.setCentralWidget(self.centralwidget)

        # MENUBAR & STATUSBAR ---------------------------
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # TEXTS -------------------------------------------
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu Petugas"))
        self.label.setText(_translate("MainWindow", "MENU PETUGAS"))
        self.label_4.setText(_translate("MainWindow", "PILIH SATU MENU"))
        self.label_2.setText(_translate("MainWindow", "KELOLA STOK"))
        self.pushButton.setText(_translate("MainWindow", "KELOLA STOK"))
        self.label_3.setText(_translate("MainWindow", "TRANSAKSI"))
        self.pushButton_2.setText(_translate("MainWindow", "TRANSAKSI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
