# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stok_darah.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        # ====== STYLE KESAMAAN DENGAN TRANSAKSI ======
        MainWindow.setStyleSheet("""
        QMainWindow {
            background-color: #f1f1f1;
            font-family: "Segoe UI";
        }

        QWidget#panel {
            background-color: white;
            border-radius: 15px;
            border: 1px solid #d0d0d0;
        }

        QLabel {
            font-weight: 600;
        }

        QComboBox, QLineEdit {
            border: 1px solid #aaaaaa;
            border-radius: 8px;
            padding: 6px;
            background: #fafafa;
            min-height: 28px;
        }

        QComboBox:hover, QLineEdit:hover {
            border: 1px solid #c00000;
        }

        QGroupBox {
            border: 1px solid #c00000;
            border-radius: 10px;
            margin-top: 6px;
            padding-top: 10px;
            font-weight: 600;
        }

        QPushButton {
            background-color: #c00000;
            color: white;
            border-radius: 10px;
            font-weight: 600;
            height: 32px;
        }
        QPushButton:hover {
            background-color: #a00000;
        }
        """)

        # ====== WIDGET UTAMA ======
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Panel putih rounded
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 140, 214, 265))
        self.widget.setObjectName("panel")

        # Layout dalam panel
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(17, 17, 17, 17)
        self.verticalLayout.setSpacing(18)

        # Judul (tanpa frame HTML)
        self.label = QtWidgets.QLabel("STOK DARAH", self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size:14pt; color:#c00000; font-weight:700;")
        self.verticalLayout.addWidget(self.label)

        # Groupbox
        self.groupBox = QtWidgets.QGroupBox("INFORMASI STOK DARAH", self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 26))
        self.verticalLayout.addWidget(self.groupBox)

        # Combo box
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(180, 30))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)

        # Input jumlah
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setPlaceholderText("Masukkan stok ...")
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 26))
        self.verticalLayout.addWidget(self.lineEdit)

        # Tombol
        self.pushButton = QtWidgets.QPushButton("TAMBAH STOK", self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 30))
        self.verticalLayout.addWidget(self.pushButton)

        # ====== MENUBAR ======
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("Stok Darah")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
