# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #f1f1f1; font-family: Segoe UI;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # CONTAINER PANEL
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(260, 80, 280, 400))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("""
            QWidget#widget {
                background-color: white;
                border-radius: 15px;
                border: 1px solid #d0d0d0;
            }
        """)

        # VERTICAL LAYOUT
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")

        # TITLE
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.label.setStyleSheet("font-size:16pt; font-weight:600; color:#c00000;")
        self.verticalLayout.addWidget(self.label, alignment=QtCore.Qt.AlignCenter)

        # Jenis Transaksi
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("font-weight: 600; font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 32))
        self.comboBox.setStyleSheet("""
            QComboBox {
                border: 1px solid #aaaaaa;
                border-radius: 8px;
                padding: 5px;
                background: #fafafa;
            }
            QComboBox:hover {
                border: 1px solid #c00000;
            }
        """)
        self.verticalLayout.addWidget(self.comboBox)

        # Golongan Darah
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("font-weight: 600; font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 32))
        self.comboBox_2.setStyleSheet("""
            QComboBox {
                border: 1px solid #aaaaaa;
                border-radius: 8px;
                padding: 5px;
                background: #fafafa;
            }
            QComboBox:hover {
                border: 1px solid #c00000;
            }
        """)
        self.verticalLayout.addWidget(self.comboBox_2)

        # Jumlah
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("font-weight: 600; font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 32))
        self.lineEdit.setPlaceholderText("Masukkan jumlah...")
        self.lineEdit.setStyleSheet("""
            QLineEdit {
                border: 1px solid #aaaaaa;
                border-radius: 8px;
                padding: 6px;
                background: #fafafa;
            }
            QLineEdit:hover {
                border: 1px solid #c00000;
            }
        """)
        self.verticalLayout.addWidget(self.lineEdit)

        # Tanggal
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet("font-weight: 600; font-size: 10pt;")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 32))
        self.lineEdit_2.setPlaceholderText("DD/MM/YYYY")
        self.lineEdit_2.setStyleSheet("""
            QLineEdit {
                border: 1px solid #aaaaaa;
                border-radius: 8px;
                padding: 6px;
                background: #fafafa;
            }
            QLineEdit:hover {
                border: 1px solid #c00000;
            }
        """)
        self.verticalLayout.addWidget(self.lineEdit_2)

        # Button
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: #c00000;
                color: white;
                border-radius: 10px;
                font-size: 10pt;
                font-weight: 600;
            }
            QPushButton:hover {
                background-color: #a00000;
            }
        """)
        self.verticalLayout.addWidget(self.pushButton)

        # SET CENTRAL
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transaksi"))
        self.label.setText(_translate("MainWindow", "TRANSAKSI"))
        self.label_2.setText(_translate("MainWindow", "Jenis Transaksi"))
        self.label_3.setText(_translate("MainWindow", "Golongan Darah"))
        self.label_4.setText(_translate("MainWindow", "Jumlah"))
        self.label_5.setText(_translate("MainWindow", "Tanggal Transaksi"))
        self.pushButton.setText(_translate("MainWindow", "SIMPAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
